import type { Metadata } from "next";
import { ClerkProvider, ClerkLoading } from "@clerk/nextjs";
import "./globals.css";

export const metadata: Metadata = {
  title: "API TOOL",
  description: "Generated by create next app",
};




export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="overflow-x-hidden">
          <ClerkLoading>
            <div className="flex items-center justify-center text-4xl bold h-[100vh]">
              Loading....
            </div>
          </ClerkLoading>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
